version: '3.7'

services:
  mongoAli:
    image: mongo:7.0.12
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ala
      MONGO_INITDB_ROOT_PASSWORD: alamakota

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9999:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ala
      ME_CONFIG_MONGODB_ADMINPASSWORD: alamakota
      ME_CONFIG_MONGODB_URL: mongodb://ala:alamakota@mongoAli:27017/