POST localhost:8081/v1/authentication/credentials/body
Content-Type: application/json

{
  "username": "ala",
  "password": "ala"
}

###
POST localhost:8081/v2/authentication/add
Content-Type: application/json
user-id:QjQ5NUJFNT
token: Bearer {{token}}

{
  "username": "ala",
  "password": "BCNDc4RDcyQTIxRDg5MEEwRERCMEI3MjY=",
  "rights": [
    "USER"
  ]
}

###
POST localhost:8081/v2/authentication/login
Content-Type: application/json

{
  "login": "Admin",
  "password": "QjQ5NUJFNTBCNDc4RDcyQTIxRDg5MEEwRERCMEI3MjY="
}
