POST localhost:8081/v2/authentication/add
Content-Type: application/json
user-id:QjQ5NUJFNT
token: Bearer {{token}}

{
  "username": "ala",
  "password": "BCNDc4RDcyQTIxRDg5MEEwRERCMEI3MjY=",
  "rights": [
    "USER"
  ]
}

###
POST localhost:8081/v2/authentication/login
Content-Type: application/json

{
  "login": "qaz",
  "password": "ZmM0ZTBkZTA4ZmE2MmY2ZmM5MGJhNTEyZTU0YmVlNDI="
}

###
POST localhost:8081/v2/token/valid?right=ADD_RESERVATIONS
Content-Type: application/json
Token: ust:name-nickname-au-ru-login-ar-rr+xst:position-nn-create-delete-company-customer-cut+name:Root+rights:[USER, TRAINEE, ADD_USERS, REMOVE_USERS, ORDER_FOOD, ADD_RESERVATIONS, REMOVE_RESERVATIONS]
