@startuml
'https://plantuml.com/sequence-diagram

autonumber
alt#gold #pink only FE
FrontendApp -> FrontendApp: User insert login and password
FrontendApp -> FrontendApp: login and password are combined, ex. login:password
FrontendApp -> FrontendApp: make MD5 hash from login:password string
FrontendApp -> FrontendApp: make Basic64 form MD5 hash
FrontendApp -> FrontendApp: split Basic64 string into half
end

alt #lightgreen
FrontendApp -> BackendApp: Send first part of credentials
FrontendApp -> BackendApp: Send second part of credentials
BackendApp -> BackendApp: Decode credentials
BackendApp -> BackendApp: Check credentials
BackendApp -> BackendApp: if credentials OK => Save in DB
BackendApp -> FrontendApp: Send Message OK/!OK
end

@enduml