  name: Docker Image CI for GHCR

  on:
    push

  jobs:
    build_and_publish:
      runs-on: ubuntu-latest
      steps:
        - uses:  actions/checkout@v3
        - name: Build and publish Docker image
          run: |
            docker login --username dicedev-pl --password ${{ secrets.GHCR_TOKEN }} ghcr.io
            docker build . -t ghcr.io/dicedev-pl/simply-auth-microservice:latest
            docker push ghcr.io/dicedev-pl/simply-auth-microservice:latest